
Vagrant.configure("2") do |config|
	config.vm.define "Server" do |server|
	  	server.vm.box = "bento/ubuntu-22.04"
  		server.vm.box_version = "202510.26.0"
		server.vm.hostname = "k3s-server"
		server.vm.synced_folder ".", "/vagrant", disabled: true
		server.vm.boot_timeout = 300
		server.vm.network "private_network", ip: "192.168.56.110"


		server.vm.provider "virtualbox" do |vb|
			vb.name = "Server"
			vb.memory = 1024
			vb.cpus = 1
			vb.gui = true
		end
		server.vm.provision "file", source: "deployment.yaml", destination: "/tmp/deployment.yaml"
		server.vm.provision "file", source: "ingress.yaml",    destination: "/tmp/ingress.yaml"
		server.vm.provision "file", source: "service.yaml",    destination: "/tmp/service.yaml"
		server.vm.provision "shell", path: "Server_Script.sh"
	end
end



###