Vagrant.configure("2") do |config|
  config.vm.define "Server" do |server|
    server.vm.box = "bento/ubuntu-22.04"
    server.vm.box_version = "202510.26.0"
	server.vm.hostname = "k3s-server"
	server.vm.synced_folder ".", "/vagrant", disabled: true
	server.vm.boot_timeout = 300
	server.vm.network "private_network", ip: "192.168.56.110"
	
	server.vm.provider "virtualbox" do |vb|
			vb.name = "Server"
			vb.memory = 2480
			vb.cpus = 1
		end
	
	server.vm.provision "file", source: "deployment.sh", destination: "/tmp/deployment.sh"
	
	server.vm.provision "file", source: "app1.yaml", destination: "/tmp/app1.yaml"
	server.vm.provision "file", source: "app2.yaml", destination: "/tmp/app2.yaml"
	server.vm.provision "file", source: "app3.yaml", destination: "/tmp/app3.yaml"
	server.vm.provision "file", source: "ingress.yaml", destination: "/tmp/ingress.yaml"

	server.vm.provision "shell", path: "Server_Script.sh"
	end
end
