version: '3'
services:
  gitlab-server:
    image: 'gitlab/gitlab-ce:19.0.1-ce.0'
    container_name: gitlab-server
    restart: always
    environment:
      GITLAB_ROOT_EMAIL: "fernandolucart@gmail.com"
      GITLAB_ROOT_PASSWORD: "SuperSecurePassword"
    ports:
      - "8080:80"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data: