version: '3'
services:
  gitlab-server:
    image: 'gitlab/gitlab-ce:19.0.1-ce.0'
    container_name: gitlab-server
    restart: always
    extra_hosts:
      - "gitlab.fernando.com=127.0.0.1"
    environment:
      GITLAB_ROOT_EMAIL: "fernandolucart@gmail.com"
      GITLAB_ROOT_PASSWORD: "SuperSecurePassword"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.fernando.com'
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - ./ssl:/etc/gitlab/ssl:ro


volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data: